apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: impulsa-prod

resources:
  - ../../base
  - limitrange.yaml
  - resourcequota.yaml
  - ingress.yaml

images:
  - name: acrimpulsaedu.azurecr.io/impulsaedu-api-service
    newTag: latest
  - name: acrimpulsaedu.azurecr.io/impulsaedu-auth-service
    newTag: latest
  - name: acrimpulsaedu.azurecr.io/impulsaedu-frontend
    newTag: latest
