apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: impulsa-dev
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: acrimpulsaedu.azurecr.io/impulsaedu-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: AUTH_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: impulsa-secrets
                  key: DB_PASSWORD
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: impulsa-config
                  key: DB_SSL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: impulsa-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
