import { SchoolStructure } from "./escuelasInterfaces";

export const mockSchools: SchoolStructure[] = [
  {
    id: "1",
    region: "San Pedro Tlaquepaque",
    school: "14EPR1234A",
    name: "Benito Juárez",
    employees: 22,
    students: 410,
    level: "Primaria",
    cct: "14EPR1234A",
    mode: "SEP-General",
    shift: "Matutino",
    address: "Av. Reforma 123",
    location: "https://maps.google.com/?q=20.674,-103.344",
    category: "Estatal",
    description: "Requiere mejora de sanitarios.",
    goal: 10000,
    progress: 6500,
    progress_pct: 65,
    status: "active",
    needs: [
      {
        id: 1,
        itemName: "Pintura para aulas",
        quantity: 30,
        unit: "Cubetas",
        amount: 3000,
      },
      {
        id: 2,
        itemName: "Reparación de baños",
        quantity: 1,
        unit: "Servicio",
        amount: 7000,
      },
    ],
  },
  {
    id: "2",
    region: "San Juan de los Lagos",
    school: "14ESN9123K",
    name: "Lázaro Cárdenas",
    employees: 31,
    students: 560,
    level: "Secundaria",
    cct: "14ESN9123K",
    mode: "SEP-General",
    shift: "Vespertino",
    address: "Calle Mar 45",
    location: "https://maps.google.com/?q=20.653,-105.225",
    category: "Federal",
    description: "Necesita equipamiento para laboratorio.",
    goal: 15000,
    progress: 7200,
    progress_pct: 48,
    status: "active",
    needs: [
      {
        id: 1,
        itemName: "Microscopios",
        quantity: 8,
        unit: "Piezas",
        amount: 12000,
      },
      { id: 2, itemName: "Reactivos", quantity: 1, unit: "Lote", amount: 3000 },
    ],
  },
  {
    id: "3",
    region: "Zapopan",
    school: "14EJN4512P",
    name: "Niños Héroes",
    employees: 14,
    students: 180,
    level: "Preescolar",
    cct: "14EJN4512P",
    mode: "SEP-General",
    shift: "Matutino",
    address: "Camino Real 222",
    location: "https://maps.google.com/?q=20.717,-103.391",
    category: "Federalizado",
    description: "Proyecto completado.",
    goal: 12000,
    progress: 12000,
    progress_pct: 100,
    status: "active",
    needs: [
      {
        id: 1,
        itemName: "Tabletas educativas",
        quantity: 20,
        unit: "Piezas",
        amount: 12000,
      },
    ],
  },
];
