apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - api-service/deployment.yaml
  - api-service/service.yaml
  - api-service/hpa.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - ingress/ingress.yaml
  - ingress/managed-cert.yaml
