apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cert-manager/clusterissuer.yaml
  - api-service/deployment.yaml
  - api-service/service.yaml
  - api-service/hpa.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
